function [matches, grid3d] = build_group_3d_absolute_density(argo_idx, meta_idx, polarity, band_label, ...
    argo_lon, argo_lat, argo_time, argo_park, argo_pf, argo_u, argo_v, argo_wpk, history_match_mask, rho, depth, ...
    meta_lon, meta_lat, meta_time, meta_track, meta_radius, meta_cx, ...
    time_window_days, depth_levels, grid_n, smooth_passes, cressman_radius_r, cressman_min_obs, ...
    match_mode, max_matches_per_group, deg_m, section_axis, section_half_width_r)

    match_timer = tic;
    if strcmp(match_mode, 'all')
        matches = build_match_rows_time_blocks(argo_idx, meta_idx, polarity, band_label, ...
            argo_lon, argo_lat, argo_time, argo_park, argo_pf, argo_u, argo_v, argo_wpk, history_match_mask, rho, depth, ...
            meta_lon, meta_lat, meta_time, meta_track, meta_radius, meta_cx, ...
            time_window_days, max_matches_per_group, deg_m);
    else
        matches = build_match_rows_nearest(argo_idx, meta_idx, polarity, band_label, ...
            argo_lon, argo_lat, argo_time, argo_park, argo_pf, argo_u, argo_v, argo_wpk, history_match_mask, rho, depth, ...
            meta_lon, meta_lat, meta_time, meta_track, meta_radius, meta_cx, ...
            time_window_days, max_matches_per_group, deg_m);
    end
    log_step(sprintf('%s %s absolute-density matching produced %d rows in %.1f s', polarity, band_label, size(matches, 1), toc(match_timer)));
    grid3d = composite_grid_3d_absolute_density(matches, rho, depth, depth_levels, grid_n, smooth_passes, cressman_radius_r, cressman_min_obs, section_axis, section_half_width_r);
    grid3d.match_mode = match_mode;
    grid3d.z_mode = 'composite_absolute_argo_density';
    grid3d.vertical_mode = 'absolute_density_stack_for_hybrid_isas_term2';
end
