function [matches, grid3d] = build_group_3d(argo_idx, meta_idx, polarity, band_label, ...
    argo_lon, argo_lat, argo_time, argo_park, argo_pf, argo_u, argo_v, argo_wpk, history_match_mask, rho, depth, ...
    meta_lon, meta_lat, meta_time, meta_track, meta_radius, meta_cx, ...
    time_window_days, grid_n, min_bin_count, smooth_passes, cressman_radius_r, cressman_min_obs, ...
    z_mode, boa_clim, depth_levels, min_drho_dz, max_rho_bracket_dz_m, match_mode, max_matches_per_group, deg_m, section_axis, section_half_width_r, vertical_mode, cache_root)

    match_timer = tic;
    if strcmp(match_mode, 'all')
        rows = build_match_rows_time_blocks(argo_idx, meta_idx, polarity, band_label, ...
            argo_lon, argo_lat, argo_time, argo_park, argo_pf, argo_u, argo_v, argo_wpk, history_match_mask, rho, depth, ...
            meta_lon, meta_lat, meta_time, meta_track, meta_radius, meta_cx, ...
            time_window_days, max_matches_per_group, deg_m);
    else
        rows = build_match_rows_nearest(argo_idx, meta_idx, polarity, band_label, ...
            argo_lon, argo_lat, argo_time, argo_park, argo_pf, argo_u, argo_v, argo_wpk, history_match_mask, rho, depth, ...
            meta_lon, meta_lat, meta_time, meta_track, meta_radius, meta_cx, ...
            time_window_days, max_matches_per_group, deg_m);
    end
    log_step(sprintf('%s %s 3D matching produced %d rows in %.1f s', polarity, band_label, size(rows, 1), toc(match_timer)));
    matches = rows;
    composite_timer = tic;
    grid3d = composite_grid_3d(matches, rho, depth, boa_clim, depth_levels, grid_n, min_bin_count, smooth_passes, cressman_radius_r, cressman_min_obs, min_drho_dz, max_rho_bracket_dz_m, section_axis, section_half_width_r, vertical_mode, cache_root, polarity, band_label, match_mode);
    log_step(sprintf('%s %s 3D composite finished in %.1f s', polarity, band_label, toc(composite_timer)));
    grid3d.match_mode = match_mode;
    grid3d.z_mode = z_mode;
    grid3d.min_drho_dz = min_drho_dz;
    grid3d.max_rho_bracket_dz_m = max_rho_bracket_dz_m;
end
